name: Raction
on:
  schedule:
    - cron: '30 22 * * 1-5'
jobs:
  render:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("magrittr", "purrr"), type = "win.binary")
        shell: Rscript {0}
      - name: Script
        run: Rscript basic_print.R


